<?php

/**
 * @file
 * impex module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\spj_impexium\ImpexSalutation;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\spj_impexium\impex;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Routing\TrustedRedirectResponse;
use Symfony\Component\HttpFoundation\Cookie;


$apiEndPoint = "";
$baseUri = "";
$accessToken = "";
$appToken = "";
$userToken = "";
$userId = "";

/**
 * Implements hook_help().
 */

function impex_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.spj_impexium':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configure Impexium Greeting at <code>/admin/config/impex-cred-configuration</code>') . '</p>';
      return $output;

    default:
  }
}


function impex_get_creds($credArr=null){
        $config = \Drupal::config('spj_impexium.creds');
        
        $dat = array();
        $dat["ACCESS_END_POINT"] = $config->get("ACCESS_END_POINT");
        $dat["APP_NAME"] = $config->get("APP_NAME");
        $dat["APP_KEY"] = $config->get("APP_KEY");
        $dat["APP_ID"] = $config->get("APP_ID");
        $dat["APP_PASSWORD"] = $config->get("APP_PASSWORD");
        $dat["APP_USER_EMAIL"] = $config->get("APP_USER_EMAIL");
        $dat["APP_USER_PASSWORD"] = $config->get("APP_USER_PASSWORD");
        $dat["CURRENT_USER_EMAIL"] = $config->get("CURRENT_USER_EMAIL");
        $dat["CURRENT_USER_PASSWORD"] = $config->get("CURRENT_USER_PASSWORD");

        return $dat;

}


function spj_impex_send_request( $url, $data, $customHeaders = null){ 
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    
    if ($customHeaders !== null ) {
        $headers = $customHeaders;
    }
    else { 
        $headers = [];
    }

    if ($data === null ) {
        curl_setopt( $ch, CURLOPT_CUSTOMREQUEST, "GET");
    }
    else { 
        curl_setopt( $ch , CURLOPT_CUSTOMREQUEST, "POST");
        $json = json_encode($data);
        $headers[] = 'Content-Length: ' . strlen($json);
        $headers[] = 'Content-Type: application/json; charset=utf-8';

        curl_setopt ($ch, CURLOPT_POSTFIELDS, $json);
    }
        
    curl_setopt ($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers);

    $ret = curl_exec($ch);
    $httpstatus = curl_getinfo($ch, CURLINFO_HTTP_CODE); # http response status code
    
    return json_decode($ret);
}

