<?php 


 function getUrl(){

    $current_uri = \Drupal::request()->getRequestUri();
    $current_uri = str_replace("/", "", $current_uri);
    return $current_uri;
}


function getFeedUrl($type){

    $path = "";
    if(isset($_REQUEST['path'])){
        $path = $_REQUEST['path'];
    }
    $feedUrl = "";
    switch($type){
        case "JT":
            
            switch($path){
                case "diversity": 
                    $feedUrl = "http://feeds.feedburner.com/jtb-diversity"; 
                    break;
                case "ethics":
                    $feedUrl = "http://feeds.feedburner.com/jtb-ethics";
                    break;
                case "foi": 
                    $feedUrl = "http://feeds.feedburner.com/jtb-foi";
                    break;
                case "freelance": 
                    $feedUrl = "http://feeds.feedburner.com/jtb-freelance";
                    break;
                case "resourcestoolsfreelancers": 
                    $feedUrl = "http://feeds.feedburner.com/jtb-freelance";
                    break;
                case "international": 
                    $feedUrl = "http://feeds.feedburner.com/jtb-ij";
                    break;
                case "resourcestoolsteachers": 
                    $feedUrl = "http://feeds.feedburner.com/jtb-jed";
                    break;
                case "resourcestoolsstudents": 
                    $feedUrl = "http://feeds.feedburner.com/jtb-jed";
                    break;
                default:
                    $feedUrl = "https://www.journaliststoolbox.org/feed/";
                    break;
            }
            

        break;
        case "Quill":
            switch($path){
                case "diversity": 
                    $feedUrl = "https://feeds.feedburner.com/quill/diversity"; 
                    break;
                case "ethics":
                    $feedUrl = "https://feeds.feedburner.com/quill/ethics";
                    break;
                case "foi": 
                    $feedUrl = "https://feeds.feedburner.com/quill/foi";
                    break;
                case "freelance": 
                    $feedUrl = "https://feeds.feedburner.com/quill/freelancing";
                    break;
                case "resourcestoolsfreelancers": 
                    $feedUrl = "https://feeds.feedburner.com/quill/freelancing";
                    break;
                case "international": 
                    $feedUrl = "https://feeds.feedburner.com/quill/ij";
                    break;
                case "resourcespublications": 
                    $feedUrl = "https://feeds.feedburner.com/spj-quill";
                    break;
                case "resourcestoolsteachers": 
                    $feedUrl = "https://feeds.feedburner.com/quill/students";
                    break;
                case "resourcestoolsstudents": 
                    $feedUrl = "https://feeds.feedburner.com/quill/students";
                    break;
                default:
                    $feedUrl = "https://www.quillmag.com/feed/";
                    break;
            }

        break;
        case "QuillPres":
            $feedUrl = "https://feeds.feedburner.com/presidentquill"; 
        break;
    }
    return $feedUrl;
}

function spj_ext_feed_makeMarkup($data){
        $first = $data['data'][0];
        $ret = "<div class='featured'><a href='" . $first["link"] . "' target='_blank'>";
        $ret .="<figure><img src='" . $first["featuredimage"] . "' alt='" . $first["title"] . "' />";
        $ret .= "</figure></a>";
        $ret .= "<h3><a href='" . $first["link"] . "' target='_blank'>" . $first["title"] . "</h3></a>";
        $ret .= "</div>";
        
        $ret .= "<div class='item-list'><ul>";
        $counter = 0;
        foreach($data['data'] as $entry){
            if($counter>0){
                $ret .= "<li>";
                $ret .= "<a href='" . $entry['link'] . "' target='_blank'>";
                $ret .= $entry["title"];
                $ret .= "</a>";
                //$ret .= "<a href='" . $entry['link'] . "' target='_blank'>";
                //$ret .= "<img src='" . $entry["featuredimage"] . "' alt='" . $entry['link'] . "' /><br />";
                //$ret .= "<p>" . $entry['description'] . "</p>";
                //$ret .= "</a>";
                $ret .= "</li>";
            }
            $counter++;

        }
        $ret .= "</ul></div>";
        return $ret;
}

function getFeedData($url){
    if($url!=null){
    $feed = simplexml_load_file($url);

    $max = 5;
    $count = 0;
    $data = array();
    $data["description"] = $feed->channel->title;
    $data["data"] = [];
    foreach ($feed->channel->item as $item) {
        if($count<$max){
            $entry = array();
            $title = (string) $item->title;
            $description = (string) $item->description;
            $link = (string) $item->link;
            $image = (string) $item->featuredimage;

            $entry["title"] = $title;
            $entry["description"] = $description;
            $entry["link"] = $link;
            $entry["featuredimage"] = $image;
            $data['data'][] = $entry;
            
        }
        $count++;
    }
    return $data;
    }


}